--- #YAML:1.0
name:                Bio-NEXUS
version:             0.69
abstract:            Bio::NEXUS - A NEXUS Application Programming Interface in Perl
license:             ~
author:              
    - Hladish, Liang, Qiu, Yang, Gopalan, & Stoltzfus (arlin.stoltzfus@nist.gov)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
